In [1]:
import pandas as pd

In [7]:
matches = pd.read_csv("PL_2019_2020.csv", index_col=0)
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
Div,,,,,,,,,,,,,,,,,,,,,
E0,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,0,H,...,3.43,-2.25,1.91,1.99,1.94,1.98,1.99,2.07,1.90,1.99
E0,10/08/2019,12:30,West Ham,Man City,0,5,A,0,1,A,...,2.91,1.75,1.95,1.95,1.96,1.97,2.07,1.98,1.97,1.92
E0,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,0,D,...,1.92,-0.50,1.95,1.95,1.98,1.95,2.00,1.96,1.96,1.92
E0,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,0,D,...,1.71,0.00,1.87,2.03,1.89,2.03,1.90,2.07,1.86,2.02
E0,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,0,D,...,1.71,0.25,1.82,2.08,1.97,1.96,2.03,2.08,1.96,1.93

In [8]:
matches.shape

(380, 105)

In [9]:
matches['HomeTeam'].value_counts()

Liverpool           19
West Ham            19
Chelsea             19
Sheffield United    19
Man City            19
Southampton         19
Norwich             19
Everton             19
Brighton            19
Aston Villa         19
Arsenal             19
Man United          19
Newcastle           19
Leicester           19
Tottenham           19
Watford             19
Crystal Palace      19
Burnley             19
Bournemouth         19
Wolves              19
Name: HomeTeam, dtype: int64

In [10]:
matches['AwayTeam'].value_counts()

Norwich             19
Man City            19
Leicester           19
Crystal Palace      19
Tottenham           19
Liverpool           19
Newcastle           19
Watford             19
West Ham            19
Bournemouth         19
Burnley             19
Chelsea             19
Arsenal             19
Wolves              19
Aston Villa         19
Brighton            19
Everton             19
Southampton         19
Sheffield United    19
Man United          19
Name: AwayTeam, dtype: int64